"""Contenido académico de los laboratorios 3 a 10.

Cada laboratorio usa identificadores propios y once etapas. El contenido fue
reorganizado desde el programa, las presentaciones MAB y las guías de trabajo.
"""

COURSE_LABS = [
    {
        "course": "Control de ruido de impacto y ruido de instalaciones",
        "course_short": "IMPACTO E INSTALACIONES",
        "labs": [
            {
                "number": 1,
                "class_number": 3,
                "id": "clase-03-impacto-instalaciones-lab-1",
                "opens_at": "2026-08-22T00:00:00-04:00",
                "source": "Clase 3",
                "focus": "Transmisión estructural, descriptores y diagnóstico",
                "stages": [
                    ("Bienvenida y ruta del laboratorio",
                     "Conocer la estructura, duración y secuencia de aprendizaje del laboratorio.",
                     "La Etapa 0 presenta la ruta completa del laboratorio, sus bloques de aprendizaje, la pausa pedagógica y la forma de trabajo.",
                     "Revisa la ruta y comienza el laboratorio."),

                    ("El edificio como sistema vibroacústico",
                     "Reconocer el edificio como sistema de transmisión vibroacústica, seguir caminos de energía y seleccionar medidas de control coherentes.",
                     "La etapa progresa desde observación y mecanismo físico hasta diagnóstico de caminos simultáneos y control de una instalación.",
                     "Observa, sigue la energía, diagnostica una pisada y una bomba, y decide dónde intervenir."),

                    ("Excitación y respuesta estructural: impedancia, movilidad, resonancia, ondas de flexión y radiación",
                     "Comprender que una misma fuerza dinámica puede producir respuestas vibratorias distintas según las propiedades dinámicas de la estructura.",
                     "La etapa relaciona fuerza, impedancia, movilidad, resonancia, modos propios, ondas de flexión y eficiencia de radiación dentro de una cadena vibroacústica.",
                     "Explora cinco interactivos para conectar fuerza, respuesta estructural, propagación y radiación acústica."),

                    ("Diagnóstico vibroacústico: de la molestia al camino de transmisión",
                     "Transformar una molestia observada en una hipótesis física sobre la fuente, el mecanismo y el camino de transmisión dominante.",
                     "La etapa organiza síntomas, evidencias y mecanismos para distinguir transmisión estructural, aérea y combinada antes de seleccionar medidas de control.",
                     "Observa síntomas, formula hipótesis, identifica caminos de transmisión y construye un diagnóstico vibroacústico."),

                    ("Física del ruido de impacto: de la fuerza de contacto a la respuesta del piso",
                     "Comprender el impacto como fuerza variable en el tiempo y relacionar interacción fuente–piso, movilidad, respuesta vibratoria y radiación.",
                     "La etapa desarrolla la cadena F(t) → F(f) → Y(f) → v(f) → Wrad(f) → Ln(f), diferenciando impacto duro/resiliente, posición de impacto, nivel absoluto y mejora.",
                     "Explora cinco interactivos para estudiar duración de contacto, tipo de piso, posición, cadena predictiva y diferencia entre Ln(f) y ΔL(f)."),

                    ("Predicción del nivel de ruido de impacto de la losa base",
                     "Estimar Lₙ,₀(f) para una losa desnuda a partir de R(f), eficiencia de radiación y régimen físico.",
                     "La etapa cierra la brecha entre la física del impacto y la predicción cuantitativa del piso base por bandas.",
                     "Explora R→Lₙ, eficiencia de radiación, regiones respecto de f_c, curva completa y selección analítico/FEM."),

                    ("Predicción de la mejora de un piso flotante: ΔLₙ(f)",
                     "Modelar la mejora espectral de un tratamiento mediante masa, rigidez, resonancia y modelos/tendencias Cremer y Vér.",
                     "Distingue transmisibilidad mecánica de mejora vibroacústica y explicita el campo de validez del piso flotante ideal.",
                     "Construye masa, mueve la resonancia, atraviesa la resonancia, compara Cremer/Vér, predice ΔLₙ y analiza puentes."),

                    ("Predicción completa del piso: de la losa base al sistema terminado",
                     "Combinar Lₙ,₀(f) y ΔLₙ(f) para obtener Lₙ,final(f), comparar alternativas y decidir bajo restricciones reales.",
                     "Integra los resultados de Etapas 5 y 6, sensibilidad, constructibilidad y campo de validez sin introducir números únicos.",
                     "Construye la predicción completa, compara tres pisos, optimiza, usa mapa de diseño, sensibilidad y modelo→obra."),

                    ("Medidas de control del ruido de instalaciones y equipos",
                     "Diagnosticar fuentes y caminos de transmisión en bombas, ventiladores, tuberías y otros equipos para seleccionar medidas de control coherentes.",
                     "El control efectivo combina acciones sobre la fuente, apoyos, conexiones, soportes, propagación estructural y radiación aérea según el mecanismo dominante.",
                     "Diagnostica equipos e instalaciones, compara soluciones y diseña una estrategia de control sobre fuente y caminos de transmisión."),

                    ("Preguntas de comprensión",
                     "Comprobar la comprensión de los conceptos trabajados durante el laboratorio.",
                     "Esta etapa integra preguntas conceptuales y aplicadas sobre transmisión, magnitudes, impacto, instalaciones y control.",
                     "Responde las preguntas de comprensión y revisa la retroalimentación."),

                    ("Desafío integrador interactivo",
                     "Resolver un caso profesional completo mediante diagnóstico, cálculo, experimentación, comparación y decisión técnica.",
                     "Integra ruido de impacto e instalaciones con los modelos de las Etapas 5–8, inspección de obra, caminos de transmisión y control combinado.",
                     "Calcula, manipula variables, compara soluciones, detecta errores, diseña medidas de control y construye el informe técnico final.")
                ],
            },
            {
                "number": 2,
                "class_number": 4,
                "id": "clase-04-impacto-instalaciones-lab-2",
                "opens_at": "2026-08-29T00:00:00-04:00",
                "source": "Clase 4",
                "focus": "Medición, ponderación, normativa y diseño de control",
                "stages": [
                    ("Del espectro al número único",
                     "Conectar L_n,final(f) del Laboratorio 1 con la evaluación ponderada del Laboratorio 2.",
                     "Recuperamos la curva espectral del piso, discutimos qué información conserva y qué información pierde un número único, e introducimos L_n,w sin adelantar el procedimiento completo.",
                     "Compara espectros, recupera tu curva y reconoce por qué menor L_n,w significa mejor comportamiento frente a impactos."),
                    ("Del nivel espectral al descriptor ponderado",
                     "Distinguir L_n, L'_n y L'_{nT} antes de interpretar sus cantidades ponderadas.",
                     "La magnitud depende del contexto de evaluación. El símbolo y el procedimiento deben corresponder al laboratorio, al elemento o al edificio.",
                     "Resuelve escenarios y selecciona qué descriptor corresponde antes de interpretar el número."),
                    ("Conoce la curva de referencia",
                     "Reconocer la forma de la curva ISO 717-2 y aprender a desplazarla sin cambiar su forma.",
                     "La curva de referencia para ruido de impacto se superpone al espectro y se desplaza verticalmente en pasos de 1 dB.",
                     "Mueve la curva de referencia sobre L_n(f), reiníciala y observa cómo cambia su posición."),
                    ("¿Qué bandas penalizan el resultado?",
                     "Identificar desviaciones desfavorables y construir la suma Σd_i.",
                     "En ruido de impacto una desviación es desfavorable cuando L_n(f) supera la referencia desplazada: d_i=max(0,L_n,i-L_ref,i).",
                     "Selecciona bandas, observa segmentos de desviación y comprueba cuáles contribuyen a Σd_i."),
                    ("Construye el número único L_n,w",
                     "Encontrar la posición límite de la referencia ISO 717-2 y leer L_n,w a 500 Hz.",
                     "La posición correcta produce la mayor suma posible de desviaciones desfavorables sin superar 32 dB.",
                     "Mueve la referencia, controla Σd_i, comprueba la posición límite y lee L_n,w del gráfico."),
                    ("Término de adaptación espectral C_I",
                     "Calcular e interpretar C_I como información espectral complementaria a L_n,w.",
                     "C_I se obtiene a partir de la suma energética del espectro de 100 a 2500 Hz; no es una mejora ni sustituye L_n,w.",
                     "Construye L_n,sum mediante suma energética, calcula C_I e interpreta dos pisos con L_n,w similar."),
                    ("Bajas frecuencias y C_I,50-2500",
                     "Visualizar cómo 50, 63 y 80 Hz pueden modificar la interpretación del piso.",
                     "El rango ampliado permite revelar problemas de baja frecuencia que un único descriptor puede ocultar.",
                     "Activa y desactiva las bajas frecuencias y compara C_I con C_I,50-2500."),
                    ("De ΔL_n(f) a ΔL_w",
                     "Transformar una reducción espectral de revestimiento en una reducción ponderada sobre piso de referencia.",
                     "Se aplica ΔL(f) al piso de referencia pesado, se pondera la curva resultante y se obtiene ΔL_w=78-L_n,r,w.",
                     "Construye paso a paso la curva del piso de referencia tratado y obtén ΔL_w."),
                    ("Interpretación profesional",
                     "Distinguir prestación del piso, reducción del revestimiento, adaptación espectral y transferibilidad.",
                     "Un número único no describe por sí solo el sistema constructivo. Piso pesado, piso liviano, ensayo y montaje condicionan la interpretación.",
                     "Recorre cuatro estaciones: L_n,w vs ΔL_w, pesado vs liviano, L_n,eq,0,w y lectura de ficha técnica."),
                    ("Evaluación final · preguntas de comprensión",
                     "Integrar el Curso 2 mediante diez preguntas de selección única.",
                     "Evaluación de 40 puntos y 20 minutos, con un solo intento, siguiendo la misma arquitectura del Curso 1 · Laboratorio 2.",
                     "Responde diez preguntas sobre Laboratorio 2 y recuperación aplicada del Laboratorio 1."),
                    ("Evaluación integradora · del espectro al diagnóstico profesional",
                     "Resolver un caso profesional completo de ruido de impacto e instalaciones.",
                     "Evaluación de 60 puntos que integra construcción manual de L_n,w, C_I, interpretación, bomba, aislamiento vibratorio, caminos paralelos y control integral.",
                     "Construye el número único visualmente, interpreta el piso y resuelve el problema de la bomba sin recibir el resultado antes del intento."),
                ],
            },
        ],
    },
    {
        "course": "Control de ruido ambiental",
        "course_short": "RUIDO AMBIENTAL",
        "labs": [
            {
                "number": 1,
                "class_number": 5,
                "id": "clase-05-ruido-ambiental-lab-1",
                "opens_at": "2026-09-12T00:00:00-03:00",
                "source": "Clase 5",
                "focus": "Descriptores, campañas, salud y análisis de casos",
                "stages": [
                    ("Introducción al laboratorio",
                     "Conocer la ruta de aprendizaje del Laboratorio 1 y el desafío profesional que conectará todas las etapas.",
                     "La experiencia sigue la secuencia escuchar → medir → describir → analizar → representar → diagnosticar.",
                     "Revisa la ruta completa y reconoce qué información viajará entre etapas."),
                    ("Ruido ambiental: fuentes, caminos y receptores",
                     "Comprender físicamente qué constituye el ambiente acústico.",
                     "El ruido ambiental depende de fuente, propagación, receptor, tiempo, frecuencia y espacio; no es solo un valor en dB.",
                     "Explora una ciudad acústica y clasifica fuentes por tipo y temporalidad."),
                    ("Del campo sonoro al sonómetro",
                     "Comprender la cadena de medición, las ponderaciones A/C/Z, la respuesta temporal y la verificación con calibrador.",
                     "El sonómetro transforma presión acústica en datos mediante micrófono, acondicionamiento, filtros, procesamiento e integración.",
                     "Desarma virtualmente un sonómetro, compara A/C/Z y ordena la secuencia de verificación."),
                    ("Laboratorio de medición real",
                     "Realizar y guardar dos mediciones educativas del propio ambiente.",
                     "Los registros conservan LAeq, Lmax, Lmin, duración y contexto para reutilizarlos en las etapas siguientes.",
                     "Abre el sonómetro online del Diplomado y construye tu registro ambiental."),
                    ("Del registro temporal a los descriptores",
                     "Interpretar cómo cambia el ruido con el tiempo mediante L(t), LAeq, extremos y percentiles.",
                     "L10, L50 y L90 describen posiciones de la distribución temporal y complementan el nivel equivalente.",
                     "Explora un registro temporal y modifica un ambiente sintético para observar cómo cambian los descriptores."),
                    ("De los datos al LAeq",
                     "Construir LAeq como promedio energético y comprender cómo se obtienen los percentiles.",
                     "Los niveles en dB no se promedian aritméticamente: se convierten a energía relativa, se ponderan por duración y se vuelve a escala logarítmica.",
                     "Resuelve el ejercicio 65–68–70–66 dB(A) y construye L10, L50 y L90."),
                    ("Del evento a las 24 horas",
                     "Distinguir la energía de un evento mediante SEL de la exposición integrada mediante LD, LE, LN y Lden.",
                     "SEL normaliza la energía de un evento; Lden integra periodos con penalizaciones convencionales de tarde y noche.",
                     "Compara eventos de distinta duración y construye una ciudad acústica de 24 horas."),
                    ("¿Dónde, cuándo y cuánto medir?",
                     "Diseñar una campaña considerando representatividad temporal y espacial.",
                     "El método exige definir objetivo, fuente, receptor, posición, periodo, duración, condiciones y descriptor.",
                     "Distribuye cinco sonómetros virtuales y recibe retroalimentación técnica basada en reglas explícitas."),
                    ("Introducción a los mapas de ruido",
                     "Comprender qué significa espacializar datos y distinguir medición, interpolación y modelación.",
                     "Un punto medido es evidencia directa; una interpolación estima entre puntos; una modelación utiliza un modelo de propagación y entradas verificadas.",
                     "Construye una representación espacial con 4, 8 y 16 puntos y abre Noise Map Lab para exploración."),
                    ("Preguntas de comprensión",
                     "Comprobar la comprensión de las Etapas 1–8 con la arquitectura evaluativa estándar del Diplomado.",
                     "Diez preguntas integran conceptos, instrumentación, descriptores, campaña y representación espacial.",
                     "Responde las diez preguntas y envía la evaluación definitiva."),
                    ("Diagnóstico acústico de un barrio",
                     "Resolver un caso profesional integral de ruido ambiental.",
                     "El caso integra reconocimiento, campaña, instrumentación, LAeq, percentiles, SEL, Lden, representación espacial y conclusión profesional.",
                     "Construye la ficha de diagnóstico acústico ambiental y declara las limitaciones del estudio."),
                ],
            },
            {
                "number": 2,
                "class_number": 6,
                "id": "clase-06-ruido-ambiental-lab-2",
                "opens_at": "2026-09-26T00:00:00-03:00",
                "source": "Clase 6 + tareas de terreno 2025",
                "focus": "Fuentes acústicas, potencia/presión y construcción de mapas de ruido",
                "stages": [
                    ("Introducción al laboratorio",
                     "Conocer la ruta desde la geometría de las fuentes hasta la construcción e interpretación de mapas de ruido.",
                     "El laboratorio diferencia fuentes puntuales, lineales y de área; potencia y presión sonora; mapas por mediciones y mapas por proyecciones.",
                     "Revisa la ruta completa y reconoce las dos evaluaciones oficiales del Curso 3."),
                    ("De la fuente al receptor",
                     "Reconocer fuente, camino de propagación y receptor como estructura básica de un problema ambiental.",
                     "El nivel observado depende de la fuente, la geometría, la distancia y el entorno de propagación.",
                     "Resuelve el caso profesional del supermercado y diseña una estrategia de investigación."),
                    ("Fuente puntual vs fuente lineal",
                     "Distinguir modelos puntuales y lineales considerando la escala geométrica del problema.",
                     "La clasificación depende de la relación entre dimensión efectiva de la fuente y distancia al receptor.",
                     "Mueve el receptor, observa el nivel y clasifica escenas según su geometría."),
                    ("Fuente de área",
                     "Comprender cuándo una superficie emisora requiere una representación de área y cómo cambia su interpretación con la distancia.",
                     "Una fuente de área distribuye emisión sobre una superficie finita; a distancias suficientemente grandes puede tender a comportarse como una fuente compacta equivalente.",
                     "Explora dimensiones de la fuente, distancia relativa y casos profesionales de fachadas, cubiertas y patios."),
                    ("Potencia sonora y presión sonora",
                     "Distinguir Lw como propiedad de emisión de Lp como nivel del campo acústico en una posición.",
                     "Lw caracteriza la fuente; Lp depende además de geometría, distancia, directividad y entorno.",
                     "Mantén fija la potencia y desplaza el receptor para observar cómo cambia Lp."),
                    ("Introducción a los mapas de ruido",
                     "Comprender qué representa un mapa de ruido y diferenciar mapas basados en mediciones de mapas obtenidos por proyección.",
                     "Los mapas por mediciones espacializan datos observados; los mapas por proyección calculan receptores a partir de fuentes y un modelo.",
                     "Compara ambos flujos de trabajo, grillas, isolíneas y significado de cada celda."),
                    ("Mapas de ruido a partir de mediciones",
                     "Construir e interpretar una superficie espacial desde puntos medidos sin confundir interpolación con medición directa.",
                     "La distribución de puntos, calidad del dato y método de interpolación condicionan la representatividad del mapa.",
                     "Modifica la red de medición y observa cómo cambia la superficie interpolada y su incertidumbre."),
                    ("Mapas de ruido por proyección",
                     "Construir una grilla calculada desde fuentes puntuales o lineales y comprender la suma energética.",
                     "Cada celda de un mapa proyectado es un receptor calculado mediante un modelo y sus supuestos.",
                     "Configura fuentes, calcula la grilla, genera isolíneas y compara fuentes puntuales y viales."),
                    ("Mini caso profesional · mapa por mediciones",
                     "Diseñar una campaña, revisar calidad de datos y construir un mapa defendible antes de la evaluación final.",
                     "Un mapa por mediciones exige objetivo, cobertura espacial, trazabilidad, control de eventos atípicos e interpretación de incertidumbre.",
                     "Selecciona puntos, depura una campaña simulada, interpola y redacta una conclusión profesional."),
                    ("Evaluación oficial · preguntas de comprensión",
                     "Evaluar los conceptos integrados de las Etapas 1–8 mediante preguntas de dificultad media–alta.",
                     "Diez preguntas oficiales combinan geometría de fuentes, propagación, Lw/Lp, interpolación, suma energética, validación y mapas por proyección.",
                     "Responde las diez preguntas y realiza un único envío definitivo de 40 puntos."),
                    ("Evaluación oficial · ruido de tráfico vehicular",
                     "Realizar una campaña real en una intersección y construir un mapa vial a partir de mediciones.",
                     "La evaluación integra 9 puntos por vía, separación de 25–30 pasos, Leq/Lmax, estabilización de 2 dB, evidencias, mapa en intervalos de 3 o 5 dB, análisis y conclusión.",
                     "Registra los 18 puntos directamente en la plataforma, genera el mapa vial y entrega la evaluación integradora de 60 puntos."),
                ],
            }
        ],
    },
    {
        "course": "Factores del ruido en el proceso de construcción",
        "course_short": "RUIDO EN CONSTRUCCIÓN",
        "labs": [
            {
                "number": 1,
                "class_number": 7,
                "id": "clase-07-construccion-lab-1",
                "opens_at": "2026-10-10T00:00:00-03:00",
                "source": "Curso 4 · Material docente + BS 5228-1:2009+A1:2014",
                "focus": "Ruido de construcción · maquinaria, propagación, modelación y control",
                "stages": [
                    ("Introducción y ruta del laboratorio", "Conocer la ruta completa del Laboratorio 1.", "La etapa presenta objetivos, tiempos, metodología y uso de Noise Map Lab sin desarrollar todavía contenido técnico.", "Revisa la ruta completa antes de comenzar."),
                    ("Maquinaria de construcción y datos acústicos de referencia", "Interpretar datos acústicos de maquinaria y actividades de obra.", "BS 5228-1 reúne datos de referencia de equipos y actividades; un valor debe leerse junto con la condición de operación, tamaño y distancia.", "Explora una biblioteca didáctica de maquinaria y reconoce qué dato puede entrar al modelo."),
                    ("Del registro BS 5228 a una fuente para modelar", "Transformar el dato acústico de referencia en una entrada trazable de modelación.", "Se parte del registro BS 5228, se identifica su descriptor y se obtiene un LWA broadband de referencia manteniendo actividad, tamaño y trazabilidad documental.", "Selecciona una maquinaria, identifica LAeq,T o LAmax, obtiene el LWA de referencia y decide cómo documentarlo antes de modelar."),
                    ("Propagación de maquinaria en aire libre", "Aplicar distancia, altura y geometría a una fuente de obra.", "La divergencia geométrica es solo una parte de la propagación; el modelo incorpora además atmósfera, suelo, barreras y geometría 3D.", "Modela una máquina en Noise Map Lab y compara receptores a distintas distancias."),
                    ("Propagación exterior completa · Agr, Abar y Cmet", "Cerrar la ecuación de propagación exterior.", "Se incorporan efecto de suelo, difracción por barreras y corrección meteorológica de largo plazo dentro del mismo esquema ISO 9613.", "Calcula Agr, Abar y Cmet y completa la ecuación de propagación."),
                    ("¿Cómo representar una obra como fuentes de ruido?", "Traducir maquinaria real a representaciones acústicas coherentes.", "Se distinguen fuentes puntuales, fuentes puntuales equivalentes y fuentes lineales viales según el fenómeno representado y el comportamiento espacial durante el período evaluado.", "Clasifica equipos, frentes de trabajo y tránsito asociado antes de construir un escenario acústico."),
                    ("Diseño y control del ruido en una obra", "Aplicar una jerarquía de control basada en fuente, trayectoria y planificación.", "Se combinan reducción de Lw, distancia, orientación, barreras, obstáculos y organización espacial para diseñar escenarios más favorables.", "Selecciona una ubicación para un generador y compara medidas combinadas."),
                    ("Ciclos de operación, simultaneidad y suma energética", "Representar el funcionamiento real de varias máquinas en un mismo período.", "Se combinan corrección temporal, simultaneidad y suma energética para obtener el nivel equivalente del escenario e identificar la fuente dominante.", "Calcula aportes equivalentes de Excavadora, Mixer, Martillo y Generador y determina cuál domina el período."),
                    ("Caso profesional guiado · introducción a Noise Map Lab", "Presentar la herramienta y desarrollar un primer caso profesional.", "Se introduce la interfaz de Noise Map Lab y se construye un escenario guiado con fuentes, receptores, terreno, ciclos y contribuciones.", "Construye el caso guiado e identifica la fuente dominante."),
                    ("Comprensión · cuestionario formativo", "Comprobar la comprensión de la clase antes del caso final.", "Diez preguntas integran BS 5228, Lp/Lw, geometría, propagación, suma energética, tiempo activo, receptores y descriptores.", "Responde las 10 preguntas y revisa la retroalimentación."),
                    ("Caso integrador final · modelación y evaluación de cumplimiento", "Resolver un caso abierto de ruido en construcción.", "El alumno recibe el predio y la maquinaria; debe buscar referencias BS 5228, definir su estrategia de modelación, seleccionar receptores y evaluar criterios didácticos.", "Construye el modelo, justifica decisiones y entrega el caso para revisión docente."),
                ],
            },
            {
                "number": 2,
                "class_number": 8,
                "id": "clase-08-construccion-lab-2",
                "opens_at": "2026-10-17T00:00:00-03:00",
                "source": "Curso 4 · Expediente SEIA 2165522433 · Conjunto Habitacional Eyzaguirre",
                "focus": "Proyecto real · reconstrucción documental, modelación y evaluación acústica",
                "stages": [
                    ("Introducción y ruta del laboratorio", "Comprender cómo se trabajará progresivamente con un proyecto real del SEIA.", "El laboratorio utiliza el Conjunto Habitacional Eyzaguirre como caso conductor y exige trazabilidad documental de cada dato utilizado.", "Revisa la ruta completa antes de comenzar."),
                    ("Conoce el proyecto · Conjunto Habitacional Eyzaguirre", "Reconstruir ubicación, escala, escenarios constructivos y maquinaria desde el expediente SEIA y la Adenda 2.", "La última referencia acústica del caso es el Anexo 05 · Estudio Ruido y Vibraciones, Versión 02 · Adenda 2. Antes de modelar, el alumno debe comprender el predio, las partes y obras y los escenarios de construcción definidos en el informe.", "Abre el expediente, localiza el proyecto, reconstruye el predio con líneas auxiliares y completa la ficha técnica usando los antecedentes documentales vigentes."),
                    ("Identifica los receptores del entorno", "Reconocer y ubicar los receptores R01–R09 de la Adenda 2.", "La etapa utiliza la Tabla 5 del último Estudio de Ruido y Vibraciones. Se distinguen receptores colindantes y no colindantes, su altura documental, zonificación y límite diurno.", "Registra R01–R09, sus coordenadas, condición de deslinde, altura y límite normativo y ubícalos en Noise Map Lab."),
                    ("Caracterización acústica de la maquinaria", "Obtener niveles globales y por bandas de las fuentes de los Escenarios 1–3.", "La Adenda 2 entrega NPS por bandas y NPSeq a 10 m en las Tablas 13–18, con referencias BS 5228 y datos del consultor. El alumno conserva la trazabilidad y realiza la conversión docente necesaria para ingresar las fuentes al modelo.", "Asocia las máquinas a referencias trazables, contrasta con las Tablas 13–18 y guarda los espectros de potencia para los frentes de trabajo."),
                    ("Modela la condición original · frentes de trabajo", "Construir los Escenarios 1–3 sin medidas de control siguiendo la Adenda 2.", "Se reproducen los frentes equivalentes de movimiento de tierra, obra gruesa, terminaciones, urbanización e IMIV. El informe considera una máquina de cada tipo operando simultáneamente y el frente concentrado en la posición desfavorable más próxima a cada receptor.", "Calcula los frentes equivalentes, aplica los parámetros ISO 9613 del informe y guarda los escenarios originales sin control."),
                    ("Resultados detallados de la condición original", "Extraer, organizar e interpretar los resultados sin medidas de control de la Adenda 2.", "Se utiliza la Tabla 27 como referencia docente: R01–R09 para los Escenarios 1–3 y receptores RIMIV para el Escenario 3. El sector se considera aproximadamente plano para centrar el ejercicio en fuentes, geometría, receptores y propagación.", "Registra los resultados del modelo, identifica máximos y excedencias respecto de 65 dB(A) y conserva la línea base original para comparar las medidas de control."),
                    ("Eventos impulsivos", "Gestionar perforación y golpes.", "El carácter impulsivo exige identificar eventos, técnica constructiva y alternativas de menor impacto.", "Compara corte, perforación y demolición."),
                    ("Relación comunitaria", "Responder con evidencia y trazabilidad.", "Aviso previo, canal único, registro y retroalimentación reducen incertidumbre, pero no reemplazan el control físico.", "Redacta un aviso responsable."),
                    ("Plan de contingencia", "Escalar cuando el control falla.", "Se detiene, verifica, corrige, documenta y reanuda bajo condiciones definidas.", "Construye un flujo de decisión."),
                    ("Caso integral", "Aplicar los tres bloques del curso.", "El caso reúne cronograma, predicción, control, monitoreo y comunicación.", "Desarrolla un plan para obra urbana."),
                    ("Evaluación individual", "Defender un plan de gestión.", "Evaluación basada en los ejercicios, tareas y caso equivalente del Curso 4.", "Entrega matriz y conclusión."),
                ],
            },
        ],
    },
    {
        "course": "Certificaciones acústicas en la edificación residencial",
        "course_short": "CERTIFICACIONES ACÚSTICAS",
        "labs": [
            {
                "number": 1,
                "class_number": 9,
                "id": "clase-09-certificaciones-lab-1",
                "opens_at": "2026-11-07T00:00:00-03:00",
                "source": "Clase 9",
                "focus": "Índices, clasificación y muestreo",
                "stages": [
                    ("Ruta de clasificación", "Comprender qué se clasifica y para qué.", "Una clase comunica desempeño bajo un esquema definido; no reemplaza las curvas ni el informe de ensayo.", "Identifica usuarios y decisiones."),
                    ("Familias de índices", "Separar aéreo, impacto, fachada e instalaciones.", "Cada familia utiliza magnitudes, métodos y sentidos de desempeño distintos.", "Asocia ocho índices."),
                    ("Laboratorio y terreno", "Distinguir Rw, R'w y DnT,w.", "Rw caracteriza elemento en laboratorio; R'w es aparente; DnT,w caracteriza diferencia estandarizada entre recintos.", "Corrige una ficha técnica."),
                    ("Fachadas", "Interpretar D2m,nT,w y términos espectrales.", "La medición de fachada incluye nivel exterior a posición definida e interior corregido; Ctr representa sensibilidad a espectros con contenido grave.", "Selecciona indicador para avenida."),
                    ("Impacto", "Interpretar L'nT,w en sentido correcto.", "En impacto, valores menores representan mejor desempeño. No debe mezclarse la lógica de clases con aislamiento aéreo.", "Ordena tres soluciones."),
                    ("Instalaciones", "Usar LAeq y LAmax con condiciones declaradas.", "El tipo de fuente y el método de operación condicionan el resultado.", "Elige descriptor para ascensor y ventilación."),
                    ("Curvas ISO 717", "Obtener números únicos sin promediar.", "La curva de referencia se ajusta mediante desviaciones; el valor único no es promedio aritmético.", "Ajusta una curva."),
                    ("Tipologías y muestreo", "Evitar generalizaciones indebidas.", "La clasificación de edificio requiere reglas de muestreo y representatividad del esquema específico; no puede afirmarse una regla universal sin revisar la norma.", "Diseña muestras por tipología."),
                    ("Comparación normativa", "No inventar equivalencias entre esquemas.", "ISO/TS 19488, UNE y NCh pueden diferir en clases, indicadores, alcance y agregación. Las tablas deben verificarse en la edición aplicable.", "Compara estructura, no números memorizados."),
                    ("Caso de edificio", "Integrar categorías y tipologías.", "Se determina clase por resultado y se aplica la regla global definida por el esquema, documentando excepciones.", "Clasifica un edificio simulado."),
                    ("Evaluación individual", "Aplicar índices y clasificación.", "Caso de 100 puntos con curvas, tipologías y conclusión.", "Entrega trazabilidad normativa."),
                ],
            },
            {
                "number": 2,
                "class_number": 10,
                "id": "clase-10-certificaciones-lab-2",
                "opens_at": "2026-11-14T00:00:00-03:00",
                "source": "Clase 10",
                "focus": "CES, verificación y expediente de certificación",
                "stages": [
                    ("Ruta CES", "Ubicar la acústica dentro del sistema.", "CES evalúa edificios de uso público y articula requerimientos obligatorios y voluntarios; no es una certificación residencial.", "Distingue CES de clasificación residencial."),
                    ("Actores y etapas", "Comprender responsabilidades.", "Mandante, asesor, evaluador y entidad administradora participan en etapas de diseño, construcción y verificación.", "Asigna entregables."),
                    ("Requisitos acústicos", "Ordenar fachada, interiores, instalaciones y acondicionamiento.", "Cada requerimiento posee alcance, indicador, evidencia y condición de evaluación propios.", "Construye una matriz de cumplimiento."),
                    ("NED y fachada", "Determinar exposición con método trazable.", "La exposición puede provenir de medición, mapas o categorías cuando el manual lo admita; debe usarse la versión vigente.", "Elige método para tres proyectos."),
                    ("Diseño de envolvente", "Controlar componentes débiles.", "Ventanas, puertas, rejillas, sellos y encuentros dominan el desempeño compuesto.", "Calcula fachada compuesta."),
                    ("Aislamiento interior", "Especificar el índice correcto.", "El requisito debe expresar magnitud, valor, recinto, método y condición; Rw de producto no reemplaza DnT,A de edificio.", "Reescribe una especificación."),
                    ("Impacto e instalaciones", "Integrar disciplinas.", "Los detalles de losa, equipos y ductos deben coordinarse para evitar puentes rígidos y ruido de servicio.", "Revisa una coordinación BIM simulada."),
                    ("Reverberación y STI", "Conectar acondicionamiento con uso.", "TR y STI evalúan aspectos distintos y dependen de ocupación, ruido de fondo y geometría. Sabine es una aproximación bajo supuestos.", "Calcula absorción requerida y discute límites."),
                    ("Evidencias", "Preparar documentación verificable.", "Memorias, fichas, ensayos, planos, especificaciones, inspecciones y mediciones deben ser coherentes entre sí.", "Detecta documentos faltantes."),
                    ("Caso asesor CES", "Cerrar brechas antes de evaluación.", "El asesor compara requisito, diseño, evidencia y riesgo de obra y propone acciones verificables.", "Completa una revisión de sala y fachada."),
                    ("Evaluación final", "Resolver un expediente equivalente.", "Evaluación individual de 100 puntos con fachada, interior, impacto, instalaciones y acondicionamiento.", "Entrega decisión y lista de evidencias."),
                ],
            },
        ],
    },
]

FUTURE_LABS = {}
for course_index, course in enumerate(COURSE_LABS, start=1):
    for lab in course["labs"]:
        lab["course_index"] = course_index
        lab["course"] = course["course"]
        lab["course_short"] = course["course_short"]
        FUTURE_LABS[lab["id"]] = lab

